import os
#!/usr/bin/env python3
"""Generate relevant documents for all venture simulations and upload to S3."""
import json, boto3, time
from datetime import datetime, timezone
from pymongo import MongoClient

MONGO_URI = os.environ.get("MONGODB_URI", "")
S3_BUCKET = "shareosimages"
S3_PREFIX = "polsia/documents"
AWS_KEY = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

s3 = boto3.client('s3', aws_access_key_id=AWS_KEY, aws_secret_access_key=AWS_SECRET, region_name='us-west-2')
client = MongoClient(MONGO_URI)
db = client.get_database('shareos')

def upload_md(venture_id, filename, content):
    key = f"{S3_PREFIX}/{venture_id}/{filename}"
    s3.put_object(Bucket=S3_BUCKET, Key=key, Body=content.encode(), ContentType='text/markdown')
    url = f"https://{S3_BUCKET}.s3.us-west-2.amazonaws.com/{key}"
    return url

def generate_pitch_deck(v):
    meta = v.get('simulation_metadata', {})
    summary = v.get('executive_summary', {})
    products = v.get('products', [])
    team = v.get('founding_team', [])
    signal = v.get('signal_origin', {})
    stages = v.get('stages', [])
    analysis = v.get('analysis', {})
    name = meta.get('venture_name', v['cmny_id'])
    vertical = meta.get('vertical', '')
    subdomain = meta.get('subdomain', '')
    tam = meta.get('tam_formatted', meta.get('tam', ''))
    target_val = summary.get('target_valuation', 0)
    current_val = summary.get('current_valuation', 0)
    takeaways = summary.get('key_takeaways', [])

    product_rows = ""
    for p in products[:5]:
        pname = p.get('name', 'Product')
        cat = p.get('category', '')
        diff = p.get('differentiator', '')
        pricing = p.get('pricing', '')
        product_rows += f"| {pname} | {cat} | {pricing} | {diff[:80]} |\n"

    team_rows = ""
    for t in team[:5]:
        tname = t.get('name', '')
        role = t.get('role', '')
        expertise = ', '.join(t.get('expertise', [])[:3]) if isinstance(t.get('expertise'), list) else str(t.get('expertise', ''))[:60]
        team_rows += f"| {tname} | {role} | {expertise} |\n"

    signals = signal.get('detection_signals', [])
    signal_items = "\n".join([f"- {s.get('signal', s) if isinstance(s, dict) else s}" for s in signals[:6]])

    stage_rows = ""
    for st in stages[:3]:
        sname = st.get('stage_name', '')
        dur = st.get('duration', '')
        ss = st.get('stage_summary', {})
        perf = ss.get('performance_score', '--')
        exe = ss.get('execution_score', '--')
        acost = ss.get('total_agent_cost', '--')
        stage_rows += f"| {sname} | {dur} | {perf} | {exe} | ${acost} |\n"

    return f"""# {name} - Investor Pitch Deck

## The Opportunity

**{subdomain}**

| Metric | Value |
|--------|-------|
| Vertical | {vertical} |
| TAM | {tam} |
| Target Valuation | ${target_val:,.0f} |
| Current Valuation | ${current_val:,.0f} |

## Executive Summary

{chr(10).join([f'- {t}' for t in takeaways[:5]])}

## Signal Origin

**Signal Strength:** {signal.get('signal_strength', '--') if isinstance(signal.get('signal_strength'), (int, float)) else signal.get('signal_strength', {}).get('score', '--')}/100

**Core Thesis:**
{signal.get('core_thesis', 'N/A')}

### Detection Signals
{signal_items}

## Products & Services

| Product | Category | Pricing | Differentiator |
|---------|----------|---------|----------------|
{product_rows}

## Founding Team

| Name | Role | Expertise |
|------|------|-----------|
{team_rows}

## Stage Progression

| Stage | Duration | Performance | Execution | Agent Cost |
|-------|----------|-------------|-----------|------------|
{stage_rows}

## Why Now

The convergence of {vertical.lower()} technology advances, growing market demand ({tam} TAM), and ShareOS's autonomous venture creation infrastructure creates a unique window to build {name} at a fraction of traditional cost.

## The Ask

Seeking seed investment to advance from Generate to Validate stage, targeting first revenue within 90 days.

---
*Generated by ShareOS Autonomous Venture System*
*{datetime.now(timezone.utc).strftime('%B %d, %Y')}*
"""


def generate_one_pager(v):
    meta = v.get('simulation_metadata', {})
    summary = v.get('executive_summary', {})
    products = v.get('products', [])
    signal = v.get('signal_origin', {})
    name = meta.get('venture_name', v['cmny_id'])
    vertical = meta.get('vertical', '')
    subdomain = meta.get('subdomain', '')
    tam = meta.get('tam_formatted', '')
    takeaways = summary.get('key_takeaways', [])

    return f"""# {name} - One Pager

## What We Do
{subdomain}

## The Problem
The {vertical.lower()} space lacks accessible, AI-driven solutions that deliver measurable outcomes at scale. Current alternatives are expensive, fragmented, or fail to leverage modern technology.

## Our Solution
{takeaways[0] if takeaways else f'{name} delivers a novel approach to {vertical.lower()} performance.'}

## Products
{chr(10).join([f'- **{p.get("name", "Product")}**: {p.get("differentiator", "")[:100]}' for p in products[:4]])}

## Market
- **TAM:** {tam}
- **Vertical:** {vertical}
- **Stage:** {meta.get('subdomain', '')[:80]}

## Traction
- Target Valuation: ${summary.get('target_valuation', 0):,.0f}
- Total Goals: {summary.get('total_goals', 0)}
- Avg Agent Work Share: {summary.get('avg_agent_work_share', '')}

## Team
Built by Share Ventures (share.vc) using ShareOS autonomous venture creation platform.

## Contact
- Web: https://{v['cmny_id'].lower()}.sharelabs.ai
- Email: hello@share.vc

---
*ShareOS Venture Simulation | {datetime.now(timezone.utc).strftime('%B %Y')}*
"""


def generate_market_analysis(v):
    meta = v.get('simulation_metadata', {})
    signal = v.get('signal_origin', {})
    summary = v.get('executive_summary', {})
    name = meta.get('venture_name', v['cmny_id'])
    vertical = meta.get('vertical', '')
    tam = meta.get('tam_formatted', meta.get('tam', ''))
    signals = signal.get('detection_signals', [])

    # Get competitor data
    comp_doc = db.polsia_okara_competitors.find_one({"$or": [
        {"domain": f"{v['cmny_id']}.sharelabs.ai"},
        {"domain": {"$regex": f"^{v['cmny_id']}$", "$options": "i"}}
    ]})
    competitors = comp_doc.get('competitors', [])[:8] if comp_doc else []
    market_overview = comp_doc.get('market_overview', {}) if comp_doc else {}
    advantages = comp_doc.get('competitive_advantages', []) if comp_doc else []

    comp_table = ""
    for c in competitors:
        cname = c.get('name', '')
        cdomain = c.get('website', c.get('domain', ''))
        csim = c.get('similarity_score', c.get('similarity', ''))
        cthreat = c.get('threat_level', c.get('market_position', ''))
        comp_table += f"| {cname} | {cdomain} | {csim}% | {cthreat} |\n"

    return f"""# {name} - Market Analysis Report

## Market Overview

| Metric | Value |
|--------|-------|
| Total Addressable Market | {tam} |
| Vertical | {vertical} |
| Market Size | {market_overview.get('market_size', 'N/A')} |
| CAGR | {market_overview.get('cagr', 'N/A')} |

## Market Trends
{chr(10).join([f'- {t}' for t in market_overview.get('trends', ['AI-driven solutions gaining traction', f'Growing demand in {vertical.lower()} technology', 'Shift toward data-driven decision making'])[:5]])}

## Detection Signals

{chr(10).join([f'### {i+1}. {s.get("signal", s) if isinstance(s, dict) else s}' + (chr(10) + f'*{s.get("detail", "")}*' if isinstance(s, dict) and s.get("detail") else '') for i, s in enumerate(signals[:8])])}

## Competitive Landscape

| Competitor | Domain | Similarity | Threat Level |
|-----------|--------|------------|-------------|
{comp_table if comp_table else '| No competitors analyzed yet | | | |'}

## Competitive Advantages
{chr(10).join([f'- {a}' for a in advantages]) if advantages else '- To be determined through validation'}

## Opportunity Assessment

**Core Thesis:** {signal.get('core_thesis', 'N/A')}

**Signal Strength:** {signal.get('signal_strength', '--') if isinstance(signal.get('signal_strength'), (int, float)) else signal.get('signal_strength', {}).get('score', '--')}/100

The {vertical} vertical presents a compelling opportunity with {tam} TAM. The convergence of market signals indicates strong demand for {name}'s approach.

---
*Market Analysis by ShareOS Intelligence | {datetime.now(timezone.utc).strftime('%B %d, %Y')}*
"""


def generate_product_spec(v):
    meta = v.get('simulation_metadata', {})
    products = v.get('products', [])
    name = meta.get('venture_name', v['cmny_id'])
    vertical = meta.get('vertical', '')

    product_sections = ""
    for i, p in enumerate(products[:5]):
        pname = p.get('name', f'Product {i+1}')
        cat = p.get('category', '')
        pricing = p.get('pricing', '')
        diff = p.get('differentiator', '')
        desc = p.get('description', '')
        tech = p.get('technology', '')

        product_sections += f"""
### {i+1}. {pname}

| Attribute | Detail |
|-----------|--------|
| Category | {cat} |
| Pricing | {pricing} |
| Differentiator | {diff} |

**Description:** {desc}

{f'**Technology:** {tech}' if tech else ''}

---
"""

    return f"""# {name} - Product Specification Document

## Overview
{name} operates in the {vertical} vertical, delivering products that leverage AI and frontier technology to unlock human potential.

## Product Portfolio ({len(products)} products)
{product_sections if product_sections else 'Product details to be defined during Validate stage.'}

## Technical Architecture

### Core Stack
- AI/ML Pipeline: LLM integration + domain-specific models
- Data Layer: Real-time ingestion and processing
- API: RESTful + WebSocket for real-time features
- Infrastructure: Cloud-native, auto-scaling

### Key Technical Requirements
- Sub-second response times for core interactions
- 99.9% uptime SLA
- HIPAA/SOC2 compliance where applicable
- Mobile-first responsive design

## Roadmap

| Phase | Timeline | Focus |
|-------|----------|-------|
| MVP | Month 1-2 | Core product loop |
| Beta | Month 3-4 | Design partner testing |
| Launch | Month 5-6 | Public availability |
| Scale | Month 7-12 | Growth + expansion |

---
*Product Spec by ShareOS | {datetime.now(timezone.utc).strftime('%B %Y')}*
"""


def generate_go_to_market(v):
    meta = v.get('simulation_metadata', {})
    summary = v.get('executive_summary', {})
    products = v.get('products', [])
    name = meta.get('venture_name', v['cmny_id'])
    vertical = meta.get('vertical', '')
    tam = meta.get('tam_formatted', '')
    takeaways = summary.get('key_takeaways', [])

    return f"""# {name} - Go-to-Market Strategy

## Target Market
- **Vertical:** {vertical}
- **TAM:** {tam}
- **ICP:** Early adopters in {vertical.lower()} seeking AI-driven solutions

## Value Proposition
{takeaways[0] if takeaways else f'{name} transforms {vertical.lower()} outcomes through AI-powered technology.'}

## GTM Phases

### Phase 1: Design Partners (Month 1-3)
| Activity | Target | Metric |
|----------|--------|--------|
| Outreach to enterprise buyers | 20 conversations | 5 design partners |
| Product demo sessions | 15 demos | 30% conversion |
| Feedback loops | Weekly check-ins | NPS > 40 |

### Phase 2: Waitlist & Pre-sales (Month 3-6)
| Channel | Strategy | Target |
|---------|----------|--------|
| Content Marketing | SEO + thought leadership | 5K organic visits/mo |
| Social | LinkedIn + Twitter campaigns | 2K followers |
| Partnerships | Integration partners | 3 partnerships |
| Paid | Targeted LinkedIn/Meta ads | $50 CAC |

### Phase 3: Public Launch (Month 6-9)
- Product Hunt launch
- Press coverage campaign
- Referral program activation
- Community building

## Pricing Strategy
{chr(10).join([f'- **{p.get("name", "Product")}:** {p.get("pricing", "TBD")}' for p in products[:4]])}

## Key Metrics to Track
| Metric | Target | Timeline |
|--------|--------|----------|
| MRR | $50K | Month 6 |
| Active Users | 500 | Month 6 |
| LTV:CAC | > 3:1 | Month 9 |
| NPS | > 50 | Ongoing |
| Churn | < 5% monthly | Month 6+ |

## Budget Allocation
| Category | % of Budget | Purpose |
|----------|-------------|---------|
| Product | 40% | Engineering + design |
| Demand | 25% | Marketing + sales |
| Operations | 15% | Infrastructure + legal |
| Team | 15% | Key hires |
| Reserve | 5% | Buffer |

---
*GTM Strategy by ShareOS | {datetime.now(timezone.utc).strftime('%B %Y')}*
"""


def generate_financial_model(v):
    meta = v.get('simulation_metadata', {})
    summary = v.get('executive_summary', {})
    name = meta.get('venture_name', v['cmny_id'])
    tam = meta.get('tam_formatted', '')
    target_val = summary.get('target_valuation', 2000000)
    agent_cost = summary.get('total_agent_cost', 0)

    return f"""# {name} - Financial Model Summary

## Key Financial Metrics

| Metric | Value |
|--------|-------|
| Target Valuation | ${target_val:,.0f} |
| TAM | {tam} |
| Total Agent Cost | ${agent_cost:,.0f} |
| Agent Cost % | {summary.get('agent_cost_pct', 'N/A')} |

## Revenue Projections (5-Year)

| Year | Revenue | Growth | Customers | ARR |
|------|---------|--------|-----------|-----|
| Year 1 | $120K | -- | 25 | $120K |
| Year 2 | $480K | 300% | 100 | $480K |
| Year 3 | $1.8M | 275% | 350 | $1.8M |
| Year 4 | $5.4M | 200% | 900 | $5.4M |
| Year 5 | $12M | 122% | 1,800 | $12M |

## Unit Economics

| Metric | Target |
|--------|--------|
| CAC | $500-2,000 |
| LTV | $5,000-15,000 |
| LTV:CAC | > 3:1 |
| Gross Margin | > 70% |
| Payback Period | < 12 months |
| Net Dollar Retention | > 120% |

## Cost Structure (Monthly at Scale)

| Category | Amount | % |
|----------|--------|---|
| Engineering | $25,000 | 35% |
| Sales & Marketing | $18,000 | 25% |
| Infrastructure | $8,000 | 11% |
| Operations | $7,000 | 10% |
| AI/Compute | $6,000 | 8% |
| G&A | $5,000 | 7% |
| Reserve | $3,000 | 4% |
| **Total** | **$72,000** | **100%** |

## Funding Requirements

| Round | Amount | Timeline | Use of Funds |
|-------|--------|----------|-------------|
| Pre-seed | $250K | Now | MVP + design partners |
| Seed | $1.5M | Month 6 | Launch + growth |
| Series A | $8M | Month 18 | Scale |

## ShareOS Cost Advantage

Traditional venture creation cost: $85K-$230K
ShareOS autonomous creation cost: ${agent_cost:,.0f}
**Cost reduction: {((1 - agent_cost/150000) * 100):.0f}%** vs traditional approach

---
*Financial Model by ShareOS | {datetime.now(timezone.utc).strftime('%B %Y')}*
"""


# Document templates mapped to workstreams
DOC_TEMPLATES = [
    ("pitch_deck", "Pitch Deck", "Investors", generate_pitch_deck),
    ("one_pager", "One Pager", "Demand", generate_one_pager),
    ("market_analysis", "Market Analysis", "Demand", generate_market_analysis),
    ("product_spec", "Product Specification", "Product", generate_product_spec),
    ("gtm_strategy", "Go-to-Market Strategy", "Demand", generate_go_to_market),
    ("financial_model", "Financial Model", "Investors", generate_financial_model),
]

def process_venture(v):
    vid = v['cmny_id']
    domain = f"{vid}.sharelabs.ai"
    ts = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
    docs = []

    for filename_base, title, workstream, generator in DOC_TEMPLATES:
        try:
            content = generator(v)
            filename = f"{filename_base}_{ts}.md"
            url = upload_md(vid, filename, content)
            docs.append({
                "title": title,
                "name": f"{title} - {vid}",
                "url": url,
                "source": "S3",
                "type": "md",
                "workstream": workstream,
                "category": workstream,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "filename": filename,
            })
            print(f"  ✓ {title}")
        except Exception as e:
            print(f"  ✗ {title}: {e}")

    # Upsert to MongoDB
    db.polsia_okara_documents.update_one(
        {"domain": domain},
        {"$set": {
            "domain": domain,
            "documents": docs,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }},
        upsert=True
    )
    return len(docs)


if __name__ == '__main__':
    sims = list(db.venture_simulations.find({}))
    print(f"Processing {len(sims)} ventures...\n")
    total = 0
    for v in sims:
        vid = v['cmny_id']
        print(f"\n=== {vid} ===")
        count = process_venture(v)
        total += count
    print(f"\n\nDone! Generated {total} documents across {len(sims)} ventures.")
